---
- hosts: galaxy
  become: yes
  gather_facts: false
  pre_tasks:
    - name: Gathering Facts
      setup:
  roles:
    ## remap user
    ## run it 1 time only
    - role: usegalaxy-eu.remap-user 
