galaxy_info:
  author: The Galaxy Project
  description: Install and Configure ProFTPD (optionally, for Galaxy Servers).
  company: The Galaxy Project
  license: AFL v3.0
  min_ansible_version: 1.8
  platforms:
  - name: Ubuntu
    versions:
    - trusty
    - utopic
    - vivid
    - wily
    - xenial
    - yakkety
  - name: Debian
    versions:
    - wheezy
    - jessie
    - stretch
  - name: EL
    versions:
    - 7
  galaxy_tags:
  - system
  - ftp
dependencies: []
