---

ansible_python_interpreter: /usr/bin/python3

# Variable that start with laniakea_ have the same name of the one used by Included roles
# we add laniakea_ to override the included roles variables in order to make the role work
# smoothly and avoiding confusion

#galaxy configuration dirs:
laniakea_galaxy_venv_dir: '{{ galaxy_install_path }}/venv' 
laniakea_galaxy_server_dir:  '{{ galaxy_install_path }}/server'
laniakea_galaxy_config_dir:  '{{ galaxy_install_path }}/config'

#laniakea galaxy vars
laniakea_galaxy_create_user: true
laniakea_galaxy_force_checkout: true
laniakea_galaxy_separate_privileges: yes
laniakea_galaxy_manage_paths: true
laniakea_galaxy_layout: root-dir
laniakea_galaxy_privsep_user: galaxy
laniakea_galaxy_mutable_config_dir: '{{ galaxy_install_path }}/config'
laniakea_galaxy_config_file: '{{ laniakea_galaxy_config_dir }}/galaxy.yml'
laniakea_galaxy_commit_id: "{{ galaxy_version }}"
laniakea_galaxy_config_style: yaml
laniakea_conda_prefix: '{{ tool_deps_path }}/_conda'

#uwsgi_vars
laniakea_uwsgi_processes: 3 
laniakea_uwsgi_threads: 4 
laniakea_uwsgi_offload_threads: 2

