---

- name: 'Include galaxy role for "mule"'
  import_tasks: install_galaxy_mule.yml
  when: uwsgi_mode == "mule"

- name: 'Include galaxy role for "zergpool"'
  import_tasks: install_galaxy_zerg.yml
  when: uwsgi_mode == "zerg"

- name: add test-toolshed 
  template:
    src: 'tool_sheds_conf.xml.j2'
    dest: '{{ laniakea_galaxy_config_dir }}/tool_sheds_conf.xml'

- name: Create log dir for uwsgi
  file:
    path: '{{ galaxy_log_path }}'
    state: directory
    owner: '{{ laniakea_galaxy_user.name }}'
    group: '{{ laniakea_galaxy_group.name }}'

- name: set default laniakea job conf 
  import_tasks: job_conf.yml
  become: yes 
  become_user: galaxy
  when: uwsgi_mode == "zerg"
